--JOB TRANSLATION
IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'T_TRANS_JOB' AND TABLE_SCHEMA = 'MAP') BEGIN
CREATE TABLE MAP.T_TRANS_JOB (LEGACY_JOB_ID VARCHAR(50), LEGACY_JOB_NAME VARCHAR(200), LEGACY_JOB_STATUS VARCHAR(20), NEW_JOB_ID VARCHAR(50), NEW_JOB_NAME VARCHAR(200), LEGACY_DATA_FOLDER_ID VARCHAR(100), INCLUDE_JOB BIT NOT NULL DEFAULT 0, DATA_FOLDER_ID VARCHAR(50));
INSERT INTO MAP.T_TRANS_JOB (LEGACY_JOB_ID, LEGACY_JOB_NAME, LEGACY_JOB_STATUS, NEW_JOB_ID, NEW_JOB_NAME, LEGACY_DATA_FOLDER_ID, INCLUDE_JOB, DATA_FOLDER_ID)
SELECT J.JOB, J.DESCRIPTION, J.STATUS, J.JOB, J.DESCRIPTION, J.Data_Folder_Id, CASE WHEN J.Status NOT IN ('Closed') THEN 1 ELSE 0 END, DATA_FOLDER_ID
FROM
    [s300].[JCM_MASTER__JOB] J;
END
GO
